version: '3'
services:
    web:
        build: .
        ports:
            - '${APP_PORT:-80}:80'
            - '5173:5173'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - CHOKIDAR_USEPOLLING='true'
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
          - laravel
    db:
        image: postgres:13
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=resu
          - POSTGRES_DB=db
        networks:
          - laravel
networks:
    laravel:
#        external: true
